version: "3"
services:
  spring1:
    image: nowgnas/zero-downtime-deploy:server # 내가 만든 이미지 이름을 지정
    container_name: blue # 컨테이너 이름 지정
    ports:
      - 8090:8090
    volumes:
      - ./:/root/ # 요것은.. 필요 없을 수도 있는데 그 이유는 아래에서..
    environment:
      USE_PROFILE: blue # Dockerfile 실행될 때 환경변수를 사용할 수 있게 지정
  spring2:
    image: nowgnas/zero-downtime-deploy:server
    container_name: green
    ports:
      - 9999:9999
    volumes:
      - ./:/root/
    environment:
      USE_PROFILE: green # Dockerfile 실행될 때 환경변수를 사용할 수 있게 지정
